CREATE TABLE AUTHOR (
    ID INT(10) NOT NULL AUTO_INCREMENT,
    USERNAME VARCHAR(64) NOT NULL,
    PASSWORD VARCHAR(64) NOT NULL,
    ACTIVE BOOLEAN,
    CONSTRAINT USERS_PK PRIMARY KEY (ID));

CREATE TABLE MESSAGE (
    ID INT(10) NOT NULL AUTO_INCREMENT,
    AUTHOR_ID INT,
	CONTENT VARCHAR(64),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT MESSAGE_PK PRIMARY KEY (ID),
    CONSTRAINT MESSAGE_AUTHOR_FK FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID));